fieldLayouts:
  f998ca73-6dd5-44a5-8c39-d824683ebf20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc455d0c-7db2-41b8-b020-c2216a065d89
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b306bb3a-6d4a-43da-9432-fecfdc4bbe35
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: baa4da62-193d-4a2d-8124-f9b1834d1bf4 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
