fieldLayouts:
  a4e8ac7b-05b6-4c77-ae5a-437fdc190afc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 77018f86-82bf-43e2-8d66-099ac5e81b6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f44846ee-32b7-4e6d-a5d0-edc0778ec61c
        userCondition: null
fs: feedsFilesystem
handle: feeds
name: Feeds
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: feedsFilesystem
transformSubpath: ''
