columnSuffix: csgflgtr
contentColumnType: text
fieldGroup: 4b6117c3-e921-44b5-9966-e771adda9159 # Common
handle: weight
instructions: null
name: Weight
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
