defaultPlacement: end
enableVersioning: true
handle: allTrials
name: 'All Trials'
propagationMethod: all
siteSettings:
  fd0d5bb9-deb9-41be-b242-95a9e340cbcd: # craft4.test
    enabledByDefault: true
    hasUrls: true
    template: trials/_all-trials.twig
    uriFormat: all-trials
type: single
